# Generated by Django 4.2.14 on 2026-04-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='category',
            field=models.CharField(choices=[('pilates-mat', 'Pilates Mat'), ('stretching', 'Stretching'), ('power-pilates', 'Power Pilates'), ('power-workout', 'Power Workout'), ('hipopresivos', 'Hipopresivos'), ('fuerza', 'Fuerza')], default='pilates-mat', max_length=50, verbose_name='Categoría'),
        ),
    ]
