# Generated by Django 4.2.14 on 2026-04-15 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claseaccess',
            options={'ordering': ['-purchased_at'], 'verbose_name': 'Acceso a clase', 'verbose_name_plural': 'Accesos a clases'},
        ),
    ]
