# Generated by Django 4.2.14 on 2026-04-17 01:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_initial'),
        ('payments', '0003_alter_claseaccess_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cart_reference',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='Referencia del carrito'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='clases.clase'),
        ),
        migrations.CreateModel(
            name='TransactionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.clase')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.transaction')),
            ],
            options={
                'verbose_name': 'Clase de transacción',
                'verbose_name_plural': 'Clases de transacción',
                'db_table': 'transaction_clases',
                'unique_together': {('transaction', 'clase')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='clases',
            field=models.ManyToManyField(blank=True, related_name='cart_transactions', through='payments.TransactionClase', to='clases.clase'),
        ),
    ]
